### ISSUE TITLE
Not working on `arm64` mac with `rosetta2`

### ISSUE THREAD

**Issue by jiedxu** [pastydev/homebrew-cmdict#5]
```console
$ arch       
arm64

$ cmdict --help        
Traceback (most recent call last):
  File "/usr/local/bin/cmdict", line 5, in <module>
    from cmdict import run_script
  File "/usr/local/Cellar/cmdict/0.1.2/libexec/lib/python3.7/site-packages/cmdict/__init__.py", line 2, in <module>
    from cmdict import run_script
  File "/usr/local/Cellar/cmdict/0.1.2/libexec/lib/python3.7/site-packages/cmdict/run_script.py", line 14, in <module>
    from cmdict.pdf_tools import extract_words
  File "/usr/local/Cellar/cmdict/0.1.2/libexec/lib/python3.7/site-packages/cmdict/pdf_tools.py", line 2, in <module>
    import fitz
  File "/usr/local/Cellar/cmdict/0.1.2/libexec/lib/python3.7/site-packages/fitz/__init__.py", line 10, in <module>
    from fitz.fitz import *
  File "/usr/local/Cellar/cmdict/0.1.2/libexec/lib/python3.7/site-packages/fitz/fitz.py", line 15, in <module>
    from . import _fitz
ImportError: dlopen(/usr/local/Cellar/cmdict/0.1.2/libexec/lib/python3.7/site-packages/fitz/_fitz.cpython-37m-darwin.so, 0x0002): symbol not found in flat namespace '_FT_Get_First_Char'
```

**Comment by jiedxu** [comment]
Not necessary, because #6 has been resolved. The installation works on `arm64` mac now.
